version: '3.7'
services:
  mongodb_container:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: muzumsu
      MONGO_INITDB_DATABASE: WinMeetDb   
      MONGO_REPLICA_HOST: host.docker.internal   
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
